package dmitriy.losev.core.core.exception

const val SAFE_CALL_FAIL = -1